name: e_gold
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  google_fonts: ^4.0.4
  fl_chart: ^0.66.0
  material_design_icons_flutter: ^7.0.7296
  intl_phone_number_input: ^0.7.4
  libphonenumber_plugin: ^0.3.3
  otp_text_field: ^1.1.3
  linear_step_indicator: ^1.0.0+3
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  http: ^1.2.0
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  onscreen_num_keyboard: ^1.0.4
  flutter_holo_date_picker: ^1.1.3
  libphonenumber: ^2.0.2
  flutter_dotenv: ^5.1.0
  # flutter_stripe: ^10.0.0
  flutter_stripe: ^10.1.1 
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  web_socket_channel: ^2.4.0
  flutter_screenutil: ^5.9.0
  simple_progress_indicators: ^0.2.0
  avatar_glow: ^3.0.1
  lottie: ^3.1.0
  change_app_package_name: ^1.1.0

#  flutter_stripe: ^10.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/egold.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 

 

flutter:
  uses-material-design: true

  assets:
    - "assets/"
    - "assets/images/"
    - "assets/icons/"
    - "assets/lottie/"
    - "assets/env/.env"
    - "assets/app_icon/"
