// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDJLJW13OBvOZNOuioQdJwWedvz67Myo',
    appId: '1:609996616069:web:2c15e4d99dec7396cad4ec',
    messagingSenderId: '609996616069',
    projectId: 'egold-1f352',
    authDomain: 'egold-1f352.firebaseapp.com',
    storageBucket: 'egold-1f352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-A6-xMYe9qr49RCxGmkPCsPXO8v2BR-c',
    appId: '1:609996616069:android:8b12efb88b34f65ccad4ec',
    messagingSenderId: '609996616069',
    projectId: 'egold-1f352',
    storageBucket: 'egold-1f352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfb3lKud5_cBzQdH97nV0iKjjy8YqkZ0',
    appId: '1:609996616069:ios:7e8a555f7b3db790cad4ec',
    messagingSenderId: '609996616069',
    projectId: 'egold-1f352',
    storageBucket: 'egold-1f352.appspot.com',
    iosBundleId: 'com.example.eGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfb3lKud5_cBzQdH97nV0iKjjy8YqkZ0',
    appId: '1:609996616069:ios:3bacdb0df4774856cad4ec',
    messagingSenderId: '609996616069',
    projectId: 'egold-1f352',
    storageBucket: 'egold-1f352.appspot.com',
    iosBundleId: 'com.example.eGold.RunnerTests',
  );
}
