// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gAfbn-26qgxeWUjIZVjdNcm81TiKYkk',
    appId: '1:748484719449:web:58717c49b5b7a526589248',
    messagingSenderId: '748484719449',
    projectId: 'e-gold-862b7',
    authDomain: 'e-gold-862b7.firebaseapp.com',
    storageBucket: 'e-gold-862b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACj5yvbu6_fFZ7Kg5OtelFyCT2Dj9yW-Q',
    appId: '1:748484719449:android:2a0004c79c882d25589248',
    messagingSenderId: '748484719449',
    projectId: 'e-gold-862b7',
    storageBucket: 'e-gold-862b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqow67Q-vZgtDjlgixyd8FtISfzdC1b2Q',
    appId: '1:748484719449:ios:fc409701dd2ff8fa589248',
    messagingSenderId: '748484719449',
    projectId: 'e-gold-862b7',
    storageBucket: 'e-gold-862b7.appspot.com',
    iosBundleId: 'com.example.eGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqow67Q-vZgtDjlgixyd8FtISfzdC1b2Q',
    appId: '1:748484719449:ios:78a757a2fd936435589248',
    messagingSenderId: '748484719449',
    projectId: 'e-gold-862b7',
    storageBucket: 'e-gold-862b7.appspot.com',
    iosBundleId: 'com.example.eGold.RunnerTests',
  );
}
